# Site
name: "Cook with Mina"
title: "Cook with Mina"
description: "Cooking blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/cwm'
google_analytics: 'G-39CMZDHR4C'
disqus: 'cookwithmina-com'
mailchimp-list: 'https://cookwithmina.us20.list-manage.com/subscribe/post?u=563450f89329d06ec0b73ef4a&amp;id=9f7753efe7'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Mina1
    display_name: Mina1
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: demina24@gmail.com
    web: https://www.cookwithmina.com
    twitter: https://twitter.com/cookwithmina
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: john
    display_name: john
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: demina24@gmail.com
    web: https://www.cookwithmina.com
    twitter: https://twitter.com/cookwithmina
    description: "Mina description"

  Mina:
    name: Mina
    display_name: Mina
    avatar: 'assets/images/avatar.png'
    email: demina24@gmail.com
    web: https://www.cookwithmina.com
    twitter: https://twitter.com/cookwithmina
    description: "Mina author description"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "todo"
adsense-data-ad-slot: "todo"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
