# Site
name: "Cook with Mina"
title: "Cook with Mina"
description: "Cooking blog with daily delicious and easy recipes!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: 'G-39CMZDHR4C'
disqus: 'cookwithmina-com'
mailchimp-list: 'https://cookwithmina.us20.list-manage.com/subscribe/post?u=563450f89329d06ec0b73ef4a&amp;id=9f7753efe7'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  mina:
    name: Mina
    display_name: Mina
    avatar: 'assets/images/avatar.png'
    email: demina24@gmail.com
    web: https://www.cookwithmina.com
    instagram: https://twitter.com/cookwithmina
    youtube: https://www.youtube.com/channel/UC9d2ER0kvzSM7lTEmfp9iuw
    description: "I am Mina and I love cooking daily! Here I am sharing my easy and tasty recipes with you! If you want more, subscribe to my YouTube channel! Enjoy!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "todo"
adsense-data-ad-slot: "todo"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
